# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b38daa425c0d9e62047f13d47f152c118a2e7738440821233cc611a3fa1d4b2dfa0d99e99e8c85e8b16a1a5fecf9a309cdd0ab47f1252664511a700c17751844

test:
  secret_key_base: 3c050539e28bd2b29de55c49092872c503a005c69eb3f3c3cd8375aecf83911c85aef3fabe3222be0b6b9181ba7da40b4390419870eca1e647e7792987f7cb85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
